name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - uses: fwcd/swift-docc-action@v1
      with:
        target: MediaLibraryKit
        output: ./docs
        hosting-base-path: MediaLibraryKit
        disable-indexing: 'true'
        transform-for-static-hosting: 'true'
